Fri Apr 05 04:32:58 EDT 2019 : Apache Derby Network Server - 10.14.2.0 - (1828579) started and ready to accept connections on port 1527
Fri Apr 05 04:32:59 EDT 2019 Thread[DRDAConnThread_2,5,main] Cleanup action starting
java.sql.SQLException: Database 'pizzadb' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR XJ004: Database 'pizzadb' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 21 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'pizzadb' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Fri Apr 05 04:32:59 EDT 2019 Thread[DRDAConnThread_2,5,main] (DATABASE = pizzadb), (DRDAID = {1}), Database 'pizzadb' not found.
----------------------------------------------------------------
Fri Apr 05 04:33:46 EDT 2019:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.14.2.0 - (1828579): instance a816c00e-0169-eca1-2a29-000028d186ce 
on database directory C:\Users\wangh_qx6\Desktop\New folder\pizzadb with class loader sun.misc.Launcher$AppClassLoader@144bcfa 
Loaded from file:/C:/Program%20Files%20(x86)/Java/jdk1.8.0_191/db-derby-10.14.2.0-bin/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_191-b12
user.dir=C:\Program Files (x86)\Java\jdk1.8.0_191\db-derby-10.14.2.0-bin
os.name=Windows 10
os.arch=x86
os.version=10.0
derby.system.home=C:\Users\wangh_qx6\Desktop\New folder
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Fri Apr 05 04:33:47 EDT 2019:
Shutting down instance a816c00e-0169-eca1-2a29-000028d186ce on database directory C:\Users\wangh_qx6\Desktop\New folder\pizzadb with class loader sun.misc.Launcher$AppClassLoader@144bcfa 
Fri Apr 05 04:33:47 EDT 2019 Thread[DRDAConnThread_2,5,main] (DATABASE = pizzadb), (DRDAID = {3}), Database 'pizzadb' shutdown.
----------------------------------------------------------------
Fri Apr 05 04:33:49 EDT 2019:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.14.2.0 - (1828579): instance a65c80ac-0169-eca1-2a29-000028d186ce 
on database directory C:\Users\wangh_qx6\Desktop\New folder\pizzadb with class loader sun.misc.Launcher$AppClassLoader@144bcfa 
Loaded from file:/C:/Program%20Files%20(x86)/Java/jdk1.8.0_191/db-derby-10.14.2.0-bin/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_191-b12
user.dir=C:\Program Files (x86)\Java\jdk1.8.0_191\db-derby-10.14.2.0-bin
os.name=Windows 10
os.arch=x86
os.version=10.0
derby.system.home=C:\Users\wangh_qx6\Desktop\New folder
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Fri Apr 05 04:54:25 EDT 2019:
Shutting down instance a65c80ac-0169-eca1-2a29-000028d186ce on database directory C:\Users\wangh_qx6\Desktop\New folder\pizzadb with class loader sun.misc.Launcher$AppClassLoader@144bcfa 
Fri Apr 05 04:54:25 EDT 2019 Thread[DRDAConnThread_3,5,main] (DATABASE = pizzadb), (DRDAID = {5}), Database 'pizzadb' shutdown.
----------------------------------------------------------------
Fri Apr 05 04:56:05 EDT 2019: Shutting down Derby engine
----------------------------------------------------------------
